import './globals.css'
import { Inter } from 'next/font/google'
import Providers from './Providers'
import Navbar from '@/components/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <div className="header-image">
        <h1 className="h1-white">Inventario de productos carnicos</h1>
    </div>
        <Providers>
          <Navbar />
          {children}</Providers> {/* Utiliza el componente Providers aquí */}
      </body>
    </html>
  )
}